# Generated by Django 2.2.7 on 2019-11-15 07:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=imagekit.models.fields.ProcessedImageField(upload_to='movies/image'),
        ),
    ]
