# Generated by Django 2.2.6 on 2019-10-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='context',
            new_name='content',
        ),
    ]
